apiVersion: v1
kind: ConfigMap
metadata:  
  name: kopia.storageconfig
data:
  .storageconfig: |-
    {
       "blobOptions": [
         { "prefix": "p", "storageClass": "STANDARD_IA" },
         { "storageClass": "STANDARD" }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ceph-callback
  name: ceph-callback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-callback
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ceph-callback
    spec:
      volumes:
      - configMap:
          defaultMode: 420
          name: kopia.storageconfig
        name: storageconfigvolume
      containers:      
      - image: michaelcourcy/ceph-callback:0.0.9-amd64
        name: ceph-callback
        volumeMounts:
        - mountPath: /etc/ceph-callback
          name: storageconfigvolume
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: ceph-callback-s3-credential
                key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: ceph-callback-s3-credential
                key: AWS_SECRET_ACCESS_KEY
        - name: AWS_ENDPOINT_URL
          valueFrom:
              secretKeyRef:
                name: ceph-callback-s3-credential
                key: AWS_ENDPOINT_URL
        - name: SECURE_ENDPOINT
          valueFrom:
              secretKeyRef:
                name: ceph-callback-s3-credential
                key: SECURE_ENDPOINT 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ceph-callback
  name: ceph-callback  
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ceph-callback
  sessionAffinity: None
  type: ClusterIP
